### PR TITLE
Drop default COPR repo

### PR DESCRIPTION
**Pull request by edewata**
The CI has been modified to no longer use a COPR repo by default and instead it will install JSS packages from `jss-builder` image.

### CODE REVIEW

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by edewata** [comment]
@fmarco76 Thanks!

**Review by ckelleyRH — COMMENTED** [review]
@edewata @fmarco76 - Is this hardcoding to use the latest image going to be OK if we branch? Do we need to maintain separate images for older branches so the CI doesn't always take the latest and potentially incompatible code from other repos? Should we document this change somewhere?

These questions may have been answered/addressed in other changes but I am slowly working my way through stuff after the holidays, so I am asking questions as I have them :+1:

**Comment by edewata** [comment]
There's a discussion about that here: https://github.com/dogtagpki/tomcatjss/pull/61
But yes, we'll need to figure out how to handle branching.

**Pull request merged**
