### PR TITLE
Run shellcheck in ldap-sdk CI

### PR DESCRIPTION
**Pull request by ckelleyRH**

### CODE REVIEW

**Review by fmarco76 — CHANGES_REQUESTED** [review]
This do not replace sonarcloud.yml so we have two sonar analyses.

**Comment by ckelleyRH** [comment]
> This do not replace sonarcloud.yml so we have two sonar analyses.

Oops, no idea how I managed that!

**Review by fmarco76 — APPROVED** [review]
I am not sure if we should put the severity error for all the projects.

Anyway we can change later so you can go ahead for now.

**Comment by ckelleyRH** [comment]
> I am not sure if we should put the severity error for all the projects.
> 
> Anyway we can change later so you can go ahead for now.

It is comparatively rare to modify the shell scripts compared to the regular development, so I would err on the side of being very strict and then loosening the rules later if it gets annoying.

**Pull request merged**
