### PR TITLE
Add Sonarcloud action

### PR DESCRIPTION
**Pull request by fmarco76**
The Sonarcloud token has to be added among the repository secrets to perform the analysis correctly

### CODE REVIEW

**Comment by ckelleyRH** [comment]
Interesting. The PKI version of this ran fine in SonarCloud without the secret, it just didn't report properly in GitHub Actions. This one doesn't appear to have run at all.

**Review by ckelleyRH — APPROVED** [review]
LGTM

**Review by edewata — APPROVED** [review]
I think the SonarCloud in PKI is actually only working in the main repo's master branch. It seems to be failing in the PRs and in my own repo, but I'll defer to you guys.

**Comment by ckelleyRH** [comment]
> I think the SonarCloud in PKI is actually only working in the main repo's master branch. It seems to be failing in the PRs and in my own repo, but I'll defer to you guys.

Yeah we were just talking about this earlier. This is because the repo secrets don't propagate to forks by default, for security reasons, so for `ldap-sdk` and `pki` the job only passes on merge; PRs and jobs in forks fail.

Interestingly, this is not true in `jss`. The difference is that for `ldap-sdk` and `pki` Sonar is run via the `SonarSource/sonarcloud-github-action@master` GitHub Action, which appears to require the secret. In `jss`, Sonar is run from the terminal as part of the Maven build:
```
mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.c.file.suffixes= -Dsonar.cpp.file.suffixes=- -Dsonar.objc.file.suffixes=-
```
We do actually attempt to provide the repo secrets to the `jss` version in a similar manner but it is not propagating in the same way as the others are not. For reasons we do not yet understand the Maven/Sonar combination does not care about the secret - it just gets on with the job.

It would be a shame to have to turn this job off for PRs, so hopefully we can fix it.

**Comment by fmarco76** [comment]
I have update the workflow so it should work also for pull request from fork repository. It is similar to pki approach so I am just merging and see if it works.

**Pull request merged**
